[package]
name = "vlecht-db"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite", "migrate"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
