[package]
name = "vlecht"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
axum = { workspace = true, features = ["ws", "macros"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
clap.workspace = true
anyhow = "1"
chrono = "0.4"
mime_guess = "2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

vlecht-db = { path = "../vlecht-db" }
vlecht-git = { path = "../vlecht-git" }
vlecht-atp = { path = "../vlecht-atp" }
flate2 = "1"
jacquard-common = { version = "0.12", features = ["crypto-k256"] }
jacquard-identity = "0.12"
russh = { version = "0.63", default-features = false, features = ["aws-lc-rs"] }
rand = "0.10.1"

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio-tungstenite = { version = "0.26" }
futures-util = "0.3"
